In [30]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [31]:
ds=pd.read_csv("dtr.csv")
ds.head()

Day   Outlook Temp. Humidity    Wind  Golf Players
0    1     Sunny   Hot     High    Weak            25
1    2     Sunny   Hot     High  Strong            30
2    3  Overcast   Hot     High    Weak            46
3    4      Rain  Mild     High    Weak            45
4    5      Rain  Cool   Normal    Weak            52

In [32]:
x=ds.iloc[:,1:5].values
y=ds.iloc[:,-1].values
print(x)
y=y.reshape(len(y),1)
print(y)
print(type(y))

[['Sunny' 'Hot' 'High' 'Weak']
 ['Sunny' 'Hot' 'High' 'Strong']
 ['Overcast' 'Hot' 'High' 'Weak']
 ['Rain' 'Mild' 'High' 'Weak']
 ['Rain' 'Cool' 'Normal' 'Weak']
 ['Rain' 'Cool' 'Normal' 'Strong']
 ['Overcast' 'Cool' 'Normal' 'Strong']
 ['Sunny' 'Mild' 'High' 'Weak']
 ['Sunny' 'Cool' 'Normal' 'Weak']
 ['Rain' 'Mild' 'Normal' 'Weak']
 ['Sunny' 'Mild' 'Normal' 'Strong']
 ['Overcast' 'Mild' 'High' 'Strong']
 ['Overcast' 'Hot' 'Normal' 'Weak']
 ['Rain' 'Mild' 'High' 'Strong']]
[[25]
 [30]
 [46]
 [45]
 [52]
 [23]
 [43]
 [35]
 [38]
 [46]
 [48]
 [52]
 [44]
 [30]]
<class 'numpy.ndarray'>


In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0,1,2,3])],remainder="passthrough")
ct.fit_transform(x)
x=np.array(ct.fit_transform(x))
print(x)

[[0. 0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0. 1. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0. 1. 1. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1. 1. 0. 1. 0.]]


In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
print(x_train)

[[0. 1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]]


In [83]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
a=[]
for i in range(4,20):
    rfr = RandomForestRegressor(n_estimators = i, random_state = 0)
    rfr.fit(x, y.ravel())
    k=r2_score(rfr.predict(x_test),y_test)
    a.append(k)
print(type(a))
b=np.array(a)
print(b)
print(type(b))
print(np.sort(b))

<class 'list'>
[ 0.38678279  0.29809465  0.4503273   0.37661633  0.1676989   0.55072653
  0.6668798   0.56719867  0.42389502  0.50792918  0.53047589  0.26435737
  0.1632644   0.1272902  -0.05463493 -0.08357406]
<class 'numpy.ndarray'>
[-0.08357406 -0.05463493  0.1272902   0.1632644   0.1676989   0.26435737
  0.29809465  0.37661633  0.38678279  0.42389502  0.4503273   0.50792918
  0.53047589  0.55072653  0.56719867  0.6668798 ]


In [78]:
print(rfr.predict(x_test))
print(y_test)

[43.73684211 35.47368421 43.26315789 44.68421053 40.47368421]
[[45]
 [35]
 [43]
 [46]
 [48]]


In [79]:
from sklearn.metrics import r2_score
print(r2_score(rfr.predict(x_train),y_train))
print(r2_score(rfr.predict(x_test),y_test))

0.6753561347617241
-0.08357406116147081
