In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
ds=pd.read_csv("temp.csv")
ds.head()

station        Date  Present_Tmax  Present_Tmin  LDAPS_RHmin  LDAPS_RHmax  \
0      1.0  30-06-2013          28.7          21.4    58.255688    91.116364   
1      2.0  30-06-2013          31.9          21.6    52.263397    90.604721   
2      3.0  30-06-2013          31.6          23.3    48.690479    83.973587   
3      4.0  30-06-2013          32.0          23.4    58.239788    96.483688   
4      5.0  30-06-2013          31.4          21.9    56.174095    90.155128   

   LDAPS_Tmax_lapse  LDAPS_Tmin_lapse  LDAPS_WS    LDAPS_LH  ...  LDAPS_PPT2  \
0         28.074101         23.006936  6.818887   69.451805  ...         0.0   
1         29.850689         24.035009  5.691890   51.937448  ...         0.0   
2         30.091292         24.565633  6.138224   20.573050  ...         0.0   
3         29.704629         23.326177  5.650050   65.727144  ...         0.0   
4         29.113934         23.486480  5.735004  107.965535  ...         0.0   

   LDAPS_PPT3  LDAPS_PPT4      lat      lon       DEM   Slope  \
0         0.0         0.0  37.6046  126.991  212.3350  2.7850   
1         0.0         0.0  37.6046  127.032   44.7624  0.5141   
2         0.0         0.0  37.5776  127.058   33.3068  0.2661   
3         0.0         0.0  37.6450  127.022   45.7160  2.5348   
4         0.0         0.0  37.5507  127.135   35.0380  0.5055   

   Solar radiation  Next_Tmax  Next_Tmin  
0      5992.895996       29.1       21.2  
1      5869.312500       30.5       22.5  
2      5863.555664       31.1       23.9  
3      5856.964844       31.7       24.3  
4      5859.552246       31.2       22.5  

[5 rows x 25 columns]

In [3]:
ds.drop("LDAPS_PPT2",axis=1,inplace=True)
ds.drop("LDAPS_PPT3",axis=1,inplace=True)
ds.drop("LDAPS_PPT4",axis=1,inplace=True)
ds.head()

station        Date  Present_Tmax  Present_Tmin  LDAPS_RHmin  LDAPS_RHmax  \
0      1.0  30-06-2013          28.7          21.4    58.255688    91.116364   
1      2.0  30-06-2013          31.9          21.6    52.263397    90.604721   
2      3.0  30-06-2013          31.6          23.3    48.690479    83.973587   
3      4.0  30-06-2013          32.0          23.4    58.239788    96.483688   
4      5.0  30-06-2013          31.4          21.9    56.174095    90.155128   

   LDAPS_Tmax_lapse  LDAPS_Tmin_lapse  LDAPS_WS    LDAPS_LH  ...  LDAPS_CC3  \
0         28.074101         23.006936  6.818887   69.451805  ...   0.161697   
1         29.850689         24.035009  5.691890   51.937448  ...   0.159444   
2         30.091292         24.565633  6.138224   20.573050  ...   0.204091   
3         29.704629         23.326177  5.650050   65.727144  ...   0.161157   
4         29.113934         23.486480  5.735004  107.965535  ...   0.178892   

   LDAPS_CC4  LDAPS_PPT1      lat      lon       DEM   Slope  Solar radiation  \
0   0.130928         0.0  37.6046  126.991  212.3350  2.7850      5992.895996   
1   0.127727         0.0  37.6046  127.032   44.7624  0.5141      5869.312500   
2   0.142125         0.0  37.5776  127.058   33.3068  0.2661      5863.555664   
3   0.134249         0.0  37.6450  127.022   45.7160  2.5348      5856.964844   
4   0.170021         0.0  37.5507  127.135   35.0380  0.5055      5859.552246   

   Next_Tmax  Next_Tmin  
0       29.1       21.2  
1       30.5       22.5  
2       31.1       23.9  
3       31.7       24.3  
4       31.2       22.5  

[5 rows x 22 columns]

In [4]:
ds.drop("LDAPS_PPT1",axis=1,inplace=True)

In [5]:
ds.head()

station        Date  Present_Tmax  Present_Tmin  LDAPS_RHmin  LDAPS_RHmax  \
0      1.0  30-06-2013          28.7          21.4    58.255688    91.116364   
1      2.0  30-06-2013          31.9          21.6    52.263397    90.604721   
2      3.0  30-06-2013          31.6          23.3    48.690479    83.973587   
3      4.0  30-06-2013          32.0          23.4    58.239788    96.483688   
4      5.0  30-06-2013          31.4          21.9    56.174095    90.155128   

   LDAPS_Tmax_lapse  LDAPS_Tmin_lapse  LDAPS_WS    LDAPS_LH  ...  LDAPS_CC2  \
0         28.074101         23.006936  6.818887   69.451805  ...   0.203896   
1         29.850689         24.035009  5.691890   51.937448  ...   0.251771   
2         30.091292         24.565633  6.138224   20.573050  ...   0.257469   
3         29.704629         23.326177  5.650050   65.727144  ...   0.226002   
4         29.113934         23.486480  5.735004  107.965535  ...   0.249995   

   LDAPS_CC3  LDAPS_CC4      lat      lon       DEM   Slope  Solar radiation  \
0   0.161697   0.130928  37.6046  126.991  212.3350  2.7850      5992.895996   
1   0.159444   0.127727  37.6046  127.032   44.7624  0.5141      5869.312500   
2   0.204091   0.142125  37.5776  127.058   33.3068  0.2661      5863.555664   
3   0.161157   0.134249  37.6450  127.022   45.7160  2.5348      5856.964844   
4   0.178892   0.170021  37.5507  127.135   35.0380  0.5055      5859.552246   

   Next_Tmax  Next_Tmin  
0       29.1       21.2  
1       30.5       22.5  
2       31.1       23.9  
3       31.7       24.3  
4       31.2       22.5  

[5 rows x 21 columns]

In [6]:
ds.replace([np.inf, -np.inf], np.nan, inplace=True)
ds.fillna(38, inplace=True)

In [7]:
x=ds.iloc[:,2:-2].values
y=ds.iloc[:,-2].values
print(x)
y=y.reshape(len(y),1)
print(y)

[[2.87000000e+01 2.14000000e+01 5.82556877e+01 ... 2.12335000e+02
  2.78500000e+00 5.99289600e+03]
 [3.19000000e+01 2.16000000e+01 5.22633972e+01 ... 4.47624000e+01
  5.14100000e-01 5.86931250e+03]
 [3.16000000e+01 2.33000000e+01 4.86904793e+01 ... 3.33068000e+01
  2.66100000e-01 5.86355566e+03]
 ...
 [2.32000000e+01 1.74000000e+01 2.29330139e+01 ... 1.95844000e+01
  2.71300000e-01 4.45134522e+03]
 [2.00000000e+01 1.13000000e+01 1.97946663e+01 ... 1.23700000e+01
  9.84746000e-02 4.32952051e+03]
 [3.76000000e+01 2.99000000e+01 9.85247345e+01 ... 2.12335000e+02
  5.17823000e+00 5.99289600e+03]]
[[29.1]
 [30.5]
 [31.1]
 ...
 [27.8]
 [17.4]
 [38.9]]


In [8]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(missing_values=np.nan,strategy="mean")
si.fit(x)
si.fit(y)

SimpleImputer()

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [10]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
sc_y=StandardScaler()
y_train=sc_y.fit_transform(y_train)
y_test=sc_y.transform(y_test)

In [11]:
from sklearn.svm import SVR
svr=SVR()
svr.fit(x_train,y_train)

c:\program files\python\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

In [12]:
y_pred=sc_y.inverse_transform(svr.predict(x_test))
print(y_pred)
print(sc_y.inverse_transform(y_test))

[27.7412376  32.60677223 32.90714744 ... 31.87016135 25.82031964
 33.62967468]
[[27.1]
 [32.2]
 [33.1]
 ...
 [31.9]
 [25.4]
 [34.3]]


In [13]:
from sklearn.metrics import r2_score
print(r2_score(y_pred,sc_y.inverse_transform(y_test)))
print(r2_score(svr.predict(x_train),y_train))

0.7733265164473317
0.7695182693665619


In [14]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor(max_depth=16,min_samples_split=8,min_samples_leaf=5)
dtr.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=16, min_samples_leaf=5, min_samples_split=8)

In [15]:
y_pred=sc_y.inverse_transform(dtr.predict(x_test))
print(y_pred)
print(sc_y.inverse_transform(y_test))

[26.01666667 32.17142857 34.44       ... 33.03333333 24.24
 33.81428571]
[[27.1]
 [32.2]
 [33.1]
 ...
 [31.9]
 [25.4]
 [34.3]]


In [16]:
from sklearn.metrics import r2_score
print(r2_score(y_pred,sc_y.inverse_transform(y_test)))

0.7387324406920714


In [17]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [18]:
y1_pred=sc_y.inverse_transform(lr.predict(x_test))
print(y1_pred)
print(sc_y.inverse_transform(y_test))

[[28.04873387]
 [32.63681358]
 [33.59346078]
 ...
 [31.30050111]
 [25.7562754 ]
 [33.64830502]]
[[27.1]
 [32.2]
 [33.1]
 ...
 [31.9]
 [25.4]
 [34.3]]


In [19]:
print(r2_score(y1_pred,sc_y.inverse_transform(y_test)))
print(r2_score(lr.predict(x_train),y_train))

0.6764803874992157
0.6310832812075498
